### PR TITLE
Sylvan optimize

### PR DESCRIPTION
**Pull request by MarkPflug**
Fixes the construction of the sylvan benchmark to pre-allocate the appropriate size of list.
Adds a benchmark for Sylvan using the strongly-typed accessors.

### CODE REVIEW

**Comment by electricessence** [comment]
Running the benchmarks again.  Will post the results when finished.

**Comment by electricessence** [comment]
@MarkPflug thanks for entertaining this.   I hope it's not too much trouble.
The purpose of this lib is not to be the most performant or the most flexible, but the simplest in that it will parse everything to a string and doesn't care about the column structure.

**Comment by electricessence** [comment]
As you posted... Similar results:

|                               Method |    Mean |    Error |   StdDev |  Median | Ratio | RatioSD |
|------------------------------------- |--------:|---------:|---------:|--------:|------:|--------:|
|                   GetAllRowsFromFile | 3.874 s | 0.1973 s | 0.5818 s | 3.906 s |  1.00 |    0.00 |
|            GetAllRowsFromFile_Sylvan | 2.899 s | 0.1231 s | 0.3628 s | 3.022 s |  0.77 |    0.17 |
| GetAllRowsFromFile_Sylvan_StrongType | 1.421 s | 0.0880 s | 0.2593 s | 1.532 s |  0.37 |    0.09 |

**Comment by MarkPflug** [comment]
I think I'm missing context on this. What are these benchmarks meant to be measuring?

**Pull request merged**
